stages:
  - lint
  - build
  - test

Lint:
  stage: lint
  tags:
    - bfs
  script: 
    - cpplint --verbose=0 src/leb128.h

Compile:
  stage: build
  tags:
    - bfs
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build/leb128_test

Test Leb128:
  stage: test
  tags:
    - bfs
  script:
    - ./build/leb128_test